#####################################################################################
#                                                                                   #
# Copyright (c) 2024, Shenyang Institute of Automation, Chinese Academy of Sciences #
#                                                                                   #
# Authors: Yanpeng Jia                                                              #
# Contact: jiayanpeng@sia.cn                                                        #
#                                                                                   #
#####################################################################################

center_pp:
    frame:
      odom_frame: camera_init
      #if points_raw
#      child_frame: aft_mapped
      #if cloud_registered
      child_frame: aft_mapped

    preprocessing:
      threshold:
        MINIMUM_RANGE: 0.5
        MAXMUM_RANGE: 100000
      cropBoxFilter:
        use: true
        size: 0.5
      voxelFilter:
        use: true
        res: 0.25 # 0.25

    save_dir: "/tmp/fast_livo_centerpoint"
    save_on_shutdown: false
